# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portrait_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
