# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0007_auto_20171209_0148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article1',
            new_name='Article',
        ),
    ]
