# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0008_auto_20171209_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='score',
            field=models.IntegerField(default=0, verbose_name='\u5206\u6570'),
        ),
    ]
