# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0012_auto_20171210_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='\u4f5c\u8005')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='\u6587\u7ae0\u72b6\u6001')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('summary', models.CharField(blank=True, help_text='\u53ef\u9009\uff0c\u5982\u82e5\u4e3a\u7a7a\u5c06\u6458\u53d6\u6b63\u6587\u7684\u524d54\u4e2a\u5b57\u7b26', max_length=54, null=True, verbose_name='\u6458\u8981')),
                ('poll_count', models.PositiveIntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570')),
                ('score', models.IntegerField(default=0, verbose_name='\u5206\u6570')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.IMG')),
                ('limit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memory.Limit', verbose_name='\u6743\u9650')),
                ('mood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memory.Mood', verbose_name='\u6240\u5c5e\u7c7b\u522b')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.RemoveField(
            model_name='article',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='article',
            name='mood',
        ),
        migrations.AlterField(
            model_name='article_detail',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='memory.Article1', verbose_name='\u6240\u5c5e\u6587\u7ae0'),
        ),
        migrations.AlterField(
            model_name='article_poll',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memory.Article1', verbose_name='\u70b9\u8d5e\u6587\u7ae0'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.Article1', verbose_name='\u8bc4\u8bba\u6587\u7ae0'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
